# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-25 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Tag name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tag is applicable?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['created_at'], 'verbose_name': 'Content', 'verbose_name_plural': 'Content'},
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Content name'),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(to='model_admin.Tag'),
        ),
    ]
