# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-25 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_admin', '0002_auto_20190825_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='model_admin.Tag'),
        ),
    ]
