# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-01 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_admin', '0003_auto_20190825_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['created_at'], 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Source', 'verbose_name_plural': 'Sources'},
        ),
        migrations.AddField(
            model_name='content',
            name='save_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Save Count'),
        ),
    ]
